ADA-126 fix bug
jgeorge37/acmwosu-db pull request #159
Opened 2021-01-06 04:43 UTC by SnobbyDragon

no caps conventions bc those arent real
try catch to silence student dup error

2021-01-06 04:59 UTC, jgeorge37 commented on acmw-db-app/components/AddAccountForm.jsx
> +            // duplicate; selects student instead
how do you know that it's a duplicate?

2021-01-06 19:21 UTC, jgeorge37 requested changes

2021-01-06 19:21 UTC, jgeorge37 commented on acmw-db-app/components/AddAccountForm.jsx
> +            // hopefully duplicate; selects student instead
this should use the error code that corresponds to attempted duplication, not another query

2021-01-06 21:58 UTC, SnobbyDragon commented
only resolved conflicts, not really merging everything from dev into this branch

2021-01-07 01:58 UTC, jgeorge37 commented
resolving conflicts always merges the whole branch

2021-01-07 01:59 UTC, SnobbyDragon commented
> resolving conflicts always merges the whole branch

rats

2021-01-07 02:06 UTC, jgeorge37 approved these changes

2021-01-07 02:15 UTC, merged