Ada 26 master
jgeorge37/acmwosu-db pull request #164
Opened 2021-01-06 21:52 UTC by cachemeifyoucan0

to test:

- create a meeting in the database that has an event code, since this code assumes that exists
- go to "https://dev-ada.herokuapp.com/attendance"
- fill out the form with the code created and submit
- check database to see if successful created new student if needed and to meeting_student table

2021-01-07 02:24 UTC, jgeorge37 requested changes
When I submit attendance for the same person for two different meetings, but I change the year of school the person is in, the year does not get updated in the database - i.e. over multiple academic years someone cannot change their year in school.

Also, if I fill out the form for a student for one meeting, their attendance is recorded, but when I fill it out for the same student for a different meeting, their attendance is not recorded. I also got a 500 internal server error in this case.

2021-01-07 03:45 UTC, cachemeifyoucan0 commented
> When I submit attendance for the same person for two different meetings, but I change the year of school the person is in, the year does not get updated in the database - i.e. over multiple academic years someone cannot change their year in school.
> 
sorry I didn't realize this had to cover over multiple years! good catch
> Also, if I fill out the form for a student for one meeting, their attendance is recorded, but when I fill it out for the same student for a different meeting, their attendance is not recorded. I also got a 500 internal server error in this case.
hm that's odd thought I def tested this I'll double check 

also - are the accounts on dev back? I just wasn't to reset my password

2021-01-07 03:50 UTC, jgeorge37 commented
ok i just realized i accidentally remade all of the accounts with the .420 student name dot nums that angela put in there instead of the real name dot nums oops

2021-01-07 04:32 UTC, cachemeifyoucan0 commented
> ok i just realized i accidentally remade all of the accounts with the .420 student name dot nums that angela put in there instead of the real name dot nums oops

lmao kk tanks

ok I fixed the year update, but I can't duplicate the double post in my local, and still my forgot password for mason.906 didn't go thru in dev

2021-01-08 19:18 UTC, jgeorge37 requested changes

2021-01-08 19:18 UTC, jgeorge37 commented on acmw-db-app/pages/api/attendance/[pid].js
> +    let current_student_yr = await pgQuery(`SELECT school_level FROM student WHERE name_dot_num = '${l_name_dot_num.toLowerCase()}'`);
I wouldn't bother checking if it is different - I'd rather have one query in every case than possibly 2 queries in some cases. If it hasn't changed no damage is done with update.

2021-01-10 18:55 UTC, jgeorge37 approved these changes

2021-01-11 03:28 UTC, merged