Ada-49
jgeorge37/acmwosu-db pull request #21
Opened 2020-09-17 04:18 UTC by SnobbyDragon

Counts the unique members (using dot number). To test:
1. Add students to the `student` table
2. Comment out the line that says to comment out in `acmw-db-app/postgres/pg-query.js`
3. Run `npm run dev`
4. Go to `http://localhost:3000/api/student/totalUniqueMembers`

Also, I don't know why my other commit for that other story card thing was there. Maybe I deliriously worked on the same branch...

2020-09-23 19:33 UTC, jgeorge37 requested changes

2020-09-23 19:33 UTC, jgeorge37 commented on acmw-db-app/pages/api/student/[pid].js
> +async function totalUniqueMembers () {
needs to incorporate “for a given academic year” i.e. check that they attended a meeting in AU__ or SP__

2020-10-02 22:25 UTC, SnobbyDragon commented
UHHHHH my thing for the other branch is still there so please ignore that or tell me to get rid of it.

2020-10-17 19:13 UTC, jgeorge37 requested changes
Should not need to involve the student table if we are just counting student ids from the meeting_student table

2020-10-28 05:03 UTC, jgeorge37 commented
Please close and re-open this as a Dev PR rather than master PR per the slack message!

2020-11-02 22:39 UTC, jgeorge37 approved these changes

2020-11-02 22:57 UTC, merged