- ADA-63, adding an exec board page/dashboard
jgeorge37/acmwosu-db pull request #29
Opened 2020-10-03 18:22 UTC by smiskus

- Adding a form to add volunteer hours for GHC attendees

To Test:
1. `npm run dev`
2. Go to localhost:3000/execdashboard
3. Click on the "Update GHC Volunteer Hours" button

2020-10-04 01:33 UTC, cachemeifyoucan0 commented
@smiskus is there a branch for this? some reason I can't check it out

2020-10-04 01:34 UTC, jgeorge37 commented
> @smiskus is there a branch for this? some reason I can't check it out

the branch name is in the PR description next to the green button

2020-10-04 01:39 UTC, cachemeifyoucan0 commented
> > @smiskus is there a branch for this? some reason I can't check it out
> 
> the branch name is in the PR description next to the green button

Ik I tried checking ADA-63 out but it says it doesn't exist

2020-10-04 01:40 UTC, cachemeifyoucan0 commented
> > > @smiskus is there a branch for this? some reason I can't check it out
> > 
> > 
> > the branch name is in the PR description next to the green button
> 
> Ik I tried checking ADA-63 out but it says it doesn't exist

oh shit I see it has a longer name oops my b

2020-10-04 01:44 UTC, cachemeifyoucan0 commented on acmw-db-app/components/GHCVolunteerForm.jsx
> +    const validateHours = (value) => {
looks great but could you also apply this to the name too? just like require their is something in the name and not blank

2020-10-04 15:34 UTC, SnobbyDragon requested changes

2020-10-04 15:34 UTC, SnobbyDragon commented on acmw-db-app/components/GHCVolunteerForm.jsx
> +            setHourError("Must provide a number greater than 0!")
I think I'd prefer it if the error messages could show up for just one (depending on which is wrong) instead of both every time.

2020-10-04 22:31 UTC, cachemeifyoucan0 approved these changes

2020-10-08 21:16 UTC, SnobbyDragon approved these changes
yay (sorry i didn't know it blocks even if someone else approves)

2020-10-08 21:17 UTC, merged